apiVersion: v1
kind: Pod
metadata:
  name: webui-pod
  labels:
    app: webui
spec:
  containers:
  - name: webui-container
    image: ghcr.io/open-webui/open-webui:main
    env:
    - name: OLLAMA_BASE_URL
      value: http://ollama-service:80
    ports:
    - containerPort: 8080
